[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
script = "contracts/script"
skip = ["**/Deploy.s.sol"]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[rpc_endpoints]
arc_testnet = "${ARC_RPC_URL}"
